tool: medusa
binary: medusa
target_placement: flag
target_flag: -h
parameters:
  username:
    flag: -u
    type: string
    required: false
  wordlist:
    flag: -P
    type: string
    required: false
  threads:
    flag: -t
    type: integer
    required: false
  service:
    flag: -M
    type: string
    required: false
  additional_args:
    type: string
    required: false
